
services:
  react-app:
    build:
      context: ./Front-End
    ports:
      - "5173:5173"
    networks:
      - app-network
  spring-backend:
    image: openjdk:21-jdk-slim
    command: [ "java", "-jar", "/app/app.jar" ]
    volumes:
      - ./Backend/GestionClient/target/GestionClient-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/GestionClientele
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      depends_on:
        -postgres
      networks:
        -app-network
  postgres:  # PostgreSQL Database
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=admin  # Database user
      - POSTGRES_PASSWORD=admin  # Database password
      - POSTGRES_DB=GestionClientele  # Database name
    volumes:
      - postgres-data:/var/lib/postgresql/data   # Data persistence between container restarts
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres-data:
    driver: local